In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000 * (toc - tic)) + "ms")

c = 0
tic = time.time()

for i in range(1000000):
    c += a[i] * b[i]

toc = time.time()

print(c)
print("For loop: " + str(1000 * (toc - tic)) + "ms")

250093.10903786987
Vectorized version: 1.9381046295166016ms
250093.10903788506
For loop: 381.09469413757324ms


In [12]:
import numpy as np
# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define a 3x1 column vector
B = np.array([[1],
              [2],
              [3]])

# Define an empty 3x1 result vector
C = np.zeros((3, 1))

# Perform vector multiplication using a for loop
for i in range(3):
    for j in range(1):
        for k in range(3):
            C[i][j] += A[i][k] * B[k][j]
        
print(C, "\n")

C = np.dot(A, B)
print(C)

[[14.]
 [32.]
 [50.]]
[[14.]
 [32.]
 [50.]] 

[[14]
 [32]
 [50]]


In [38]:
import numpy as np
import math

# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A_exp = np.zeros((3,3))

for i in range(3):
    for j in  range(3):
        A_exp[i][j] = math.exp(A[i][j])
    
print(A_exp, "\n")

# Calculate the element-wise exponential of A using numpy.exp()
A_exp = np.exp(A)
print(A_exp, "\n")

# Calculate the element-wise logarithm of A using numpy.log()
A_log = np.log(A)
print(A_log, "\n")

# Calculate the element-wise absoulte of A using numpy.abs()
A_abs = np.abs(A)
print(A_abs, "\n")

# Calculate the element-wise max compare to reference number of A using numpy.max( , )
A_max = np.max(A, 0)
print(A_max, "\n")

# Calculate the element-wise square of A using numpy.square()
A_square = np.square(A)
print(A_square, "\n")

# Define a 3x3 matrix
A = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])


# Calculate the element-wise inverse of A using numpy.reciprocal()
A_inv = np.reciprocal(A)
print(A_inv)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[7 8 9] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]
